---
title: " "
pagetitle: "Sabina Mora"
---

<link rel="stylesheet" href="styles.css" type="text/css">

&nbsp;  


**City of Mountain View – Economic Development Specialist**

* Responsible for designing guidelines, administrative framework, contract compliance, and evaluating economic impact for small business loan and grant incentive programs. 
* Coordinate across city departments to assist businesses with local regulations and compliance, including permits, development review, building and code enforcement, and business licensing. 
* Coordinate legislative process to authorize tax assessment annually, develop city council reports and presentations, draft and redline city contracts governing the use of funds generated from the district. 

**City of Austin – Senior Planner**

* Served as the project manager for land use plan amendments for real estate development projects. 
* Conducted advanced demographic and economic research, needs/community assessments, and plan development. 
* Designed, coordinated, and executed outreach and communications strategies for city land use plans.

|           Work Samples:

|            **[Imagine Austin Centers and Corridors: North Lamar Community Inventory (2019)](./files/NLamar.pdf)**



**Empire State Development – Loans & Grants Project Manager**

* Project manager for more than two hundred economic development contracts valued at $200 million in loans, grants, and tax credits; incentives varied in size from thousands to $35 million. 
* Project manager for $20 million grant fund focused on downtown revitalization: responsible for evaluating hundreds of applications and recommending grants for 30 projects. 
* Provided information to dozens of companies on location factors including available incentives, quality of life, supply/demand chains, infrastructure, and labor quality/availability.

|           Work Samples:

|            **[Greater Binghamton Fund Strategic Investment Plan (2018)](./files/GBF_SIP.pdf)**



**Capitalize Albany Corporation – Senior Economic Development Specialist**

* Monitored contract compliance for >100 business expansion and real estate development incentive agreements, including grants, loans, and tax abatements. 
* Project Manager responsible for financial analysis (identifying gaps in project funding sources), fiscal impact (on the municipal budget), and cost/benefit analysis (direct and indirect economic impacts and community benefits) as well as negotiating tax abatement agreements for 12 real estate development projects. 
* Developed the agency’s tax abatement policy which standardized the calculation of project incentives based on fiscal impact and community benefits. Also developed standard incentive contracts and compliance procedures. 

|           Work Samples:

|            **[City of Albany Industrial Development Agency 2016 Year in Review](./files/AlbID_A2016.pdf)**
|            **[City of Albany Industrial Development Agency 2015 Annual Report](./files/AlbIDA_2015.pdf)**



**City of Binghamton – Economic Development Specialist**

* Represented the City for a dozen site selection visits for small and large business expansions and relocations.
* Developed and executed business expansion and retention strategies, such as a business visitation program; visited more than 50 businesses to discuss needs and challenges. 
* Provided technical assistance to 5 large-scale real estate development projects, guiding developers through the local and state regulatory process. 

|           Work Samples:

|            **[Public Investment & Leverage 2006-2012](./files/Maps_Bing.pdf)**
|            **[Downtown Parking & Street Map](./files/bing_dt_map.pdf)**
